version: 0.2

phases:
  pre_build:
    commands:
      - echo Pre Build starting
      - wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
      - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
      - apt update -y
      - apt install terraform -y
      - terraform init -migrate-state
      - pip install checkov
  build:
    commands:
      - echo Build starting
      - terraform plan -var-file=$ENVIRONMENT.tfvars -out=$ENVIRONMENT-tfplan
      - checkov -s -d ./ > checkov.result.txt      
  post_build:
    commands:
      - echo Post build starting
      - aws sns publish --topic-arn $SEC_TOPIC_ARN --subject "Validate Checkov Result" --message file://checkov.result.txt
      - aws s3 cp --region=us-east-1 "$ENVIRONMENT-tfplan" "s3://$S3_BUCKET"
      - echo Post build completed