version: 0.2

phases:
  pre_build:
    commands:
      - echo Pre Build here
      - wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
      - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
      - apt update -y
      - apt install terraform -y
      - terraform init -migrate-state
      - aws s3 cp --region=us-east-1 "s3://$S3_BUCKET/$ENVIRONMENT-tfplan" "tfplan"
  build:
    commands:
      - echo Build starting
      - "terraform apply tfplan"
  post_build:
    commands:
      - echo Build completed